# Generated by Django 2.2.17 on 2021-04-04 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month_number', models.IntegerField()),
                ('month_name', models.CharField(max_length=30)),
                ('day_of_month', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('year_month', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('subscription_id', models.CharField(max_length=100)),
                ('policy_start_date', models.DateTimeField(blank=True)),
                ('policy_end_date', models.DateTimeField(blank=True)),
                ('underwriter', models.TextField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ViewUsersStatus',
            fields=[
                ('year_month', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('active_from', models.CharField(max_length=50)),
                ('user_life_cycle_status', models.CharField(max_length=50)),
                ('lapsed_months', models.IntegerField()),
                ('month_number', models.IntegerField()),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Policy')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('finance_transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('reason', models.CharField(max_length=30)),
                ('premium', models.IntegerField()),
                ('ipt', models.IntegerField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Policy')),
            ],
        ),
    ]
