# Generated by Django 2.2.17 on 2021-04-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewusersstatus',
            name='policy',
        ),
        migrations.AddField(
            model_name='viewusersstatus',
            name='policy_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
