# Generated by Django 2.2.17 on 2021-04-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210404_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewUsersLifeCycleStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_month', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('active_from', models.CharField(max_length=50)),
                ('user_life_cycle_status', models.CharField(max_length=50)),
                ('lapsed_months', models.IntegerField()),
                ('policy_id', models.CharField(blank=True, max_length=50, null=True)),
                ('month_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ViewUsersStatus',
        ),
    ]
