# Generated by Django 2.2.17 on 2021-04-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210404_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewuserslifecyclestatus',
            name='underwriter',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
    ]
